# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

theme = "congo"
baseURL = "https://daharmattan1.github.io/markets2mountains/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 25

# Clean permalinks (slug only, no dates)
[permalinks]
  posts = "/:slug/"

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
